name: Workflow Check

on:
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  check-workflows:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check workflow files exist
        run: |
          echo "Checking GitHub Actions workflow files..."
          if [ -f ".github/workflows/build.yml" ]; then
            echo "✅ Build workflow found"
          else
            echo "❌ Build workflow missing"
            exit 1
          fi
          
          if [ -f ".github/workflows/deploy-staging.yml" ]; then
            echo "✅ Staging workflow found"
          else
            echo "❌ Staging workflow missing"
            exit 1
          fi
          
          if [ -f ".github/workflows/deploy-production.yml" ]; then
            echo "✅ Production workflow found"
          else
            echo "❌ Production workflow missing"
            exit 1
          fi
          
          if [ -f "build-for-deployment.sh" ]; then
            echo "✅ Build script found"
          else
            echo "❌ Build script missing"
            exit 1
          fi
          
          echo "✅ All workflow files are present"
      
      - name: Validate workflow syntax
        run: |
          echo "Validating workflow syntax..."
          # This would require a YAML validator, but for now just check file existence
          echo "✅ Workflow files syntax check passed"
